#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 12 15:51:13 2019

@author: viveksinghbhadouriya
This code will help you to setup the Python connection with Microstrtagey (version 10.11 and above)

 Prerequisite: Mistrio installation
 pip install mstrio

"""


import warnings
warnings.simplefilter('ignore')

#import _requestes
from mstrio import microstrategy
from mstrio.api import authentication
from scipy import stats
from scipy.stats import norm
import unicodecsv
import pandas as pd
import getpass
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt


### Parameters ###
api_login = input("Enter User Name: ")
api_password = getpass.getpass(prompt='Password: ', stream=None)
api_login_mode = 16
#project_id = ''
api_project=input("Enter Project you want to connect: ")
base_url = input("Enter Microstartegy Server URL: ")
base_url=base_url +"/MicroStrategyLibrary/api"
#'https://<url>/MicroStrategyLibrary/api';
#root_folder = 'Shared Reports'
#type_object = 55 #55 is document/dossier ; 3 is report/cube
#certifiedStatus = 'ALL' #CERTIFIED_ONLY , ALL
#get_ancestors = 'true'
#limit_search = -1

def login():
    conn = microstrategy.Connection(base_url=base_url, username=api_login,
                    password=api_password, project_name=api_project,login_mode=api_login_mode)
    conn.connect()
    # To get the Icube id right click on the cube and take the ID
    c_data=conn.get_cube(cube_id='<Mention the ICube ID>')
    print(c_data)
    conn.close()
    
def main():
    login()  
    
if __name__== '__main__':
    main()
